### ISSUE TITLE
compile error with ghc-8.2.0-rc1

### ISSUE THREAD

**Issue by alexanderkjeldaas** [lpsmith/postgresql-libpq#37]
stackage lts-8.9

```
    [1 of 1] Compiling Main             ( /private/var/folders/pq/xz5t60ld4v10j_tt7bd25rfhtzqwq8/T/stack3840/postgresql-libpq-0.9.3.0/Setup.hs, /private/var/folders/pq/xz5t60ld4v10j_tt7bd25rfhtzqwq8/T/stack3840/postgresql-libpq-0.9.3.0/.stack-work/dist/x86_64-osx/Cabal-2.0.0.0/setup/Main.o )

    /private/var/folders/pq/xz5t60ld4v10j_tt7bd25rfhtzqwq8/T/stack3840/postgresql-libpq-0.9.3.0/Setup.hs:17:16: error:
        • Data constructor not in scope: FlagName :: [Char] -> FlagName
        • Perhaps you meant one of these:
            variable ‘flagName’ (imported from Distribution.PackageDescription),
            variable ‘mkFlagName’ (imported from Distribution.PackageDescription),
            variable ‘unFlagName’ (imported from Distribution.PackageDescription)
       |
    17 |     if lookup (FlagName "use-pkg-config")
       |                ^^^^^^^^

    /private/var/folders/pq/xz5t60ld4v10j_tt7bd25rfhtzqwq8/T/stack3840/postgresql-libpq-0.9.3.0/Setup.hs:27:39: error:
        • Couldn't match expected type ‘Distribution.Types.UnqualComponentName.UnqualComponentName’
                      with actual type ‘[Char]’
        • In the expression: "runtests"
          In the expression: ("runtests", bi)
          In the expression: [("runtests", bi)]
       |
    27 |                           (Just bi, [("runtests", bi)]) (localPkgDescr lbi)
       |                                       ^^^^^^^^^^
```

using stack.yaml setup like this:
```
compiler: ghc-8.2.0.20170404
compiler-check: match-exact
setup-info:
  ghc:
    linux64:
      8.2.0.20170404:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc1/ghc-8.2.0.20170404-x86_64-deb8-linux.tar.xz
        content-length: 138846620
        sha1: 3fd303b5753b095ce020131405dcf43199e6b447
    macosx:
      8.2.0.20170404:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc1/ghc-8.2.0.20170404-x86_64-apple-darwin.tar.xz
        content-length: 124010408
        sha1: 301de7f5b6ed87ade2182ed2552df2ef39b98b03
    # The Windows build is broken :(
    # https://www.reddit.com/r/haskell/comments/64he68/announce_ghc_821_release_candidate_1/dg2b5ei/
    windows64:
      8.2.0.20170404:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc1/ghc-8.2.0.20170404-x86_64-unknown-mingw32.tar.xz
        content-length: 173924808
        sha1: 5cfd11230ff95423a7b19104232247e3fab0dba3
```
